name: Deploy Full Stack Application

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22.5.1'  # Use Node.js version 22.5.1

    # Backend Deployment Steps
    - name: Install Backend Dependencies
      working-directory: banner-backend
      run: npm install

    - name: Skip Backend Build
      run: echo "No build step required for backend"

    # Frontend Deployment Steps
    - name: Install Frontend Dependencies
      working-directory: banner-frontend
      run: npm install

    - name: Build Frontend
      working-directory: banner-frontend
      run: npm run build

    # SSH Setup
    - name: Set Up SSH Key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Add Server to Known Hosts
      run: |
        ssh-keyscan ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

    # Deploy to VPS
    - name: Deploy Backend to VPS
      run: |
        rsync -avz --delete --exclude='node_modules' --exclude='.git' banner-backend/ ${{ secrets.USERNAME }}@${{ secrets.SERVER_IP }}:/home/vivek_project/banner-backend/

    - name: Deploy Frontend to VPS
      run: |
        rsync -avz --delete --exclude='node_modules' --exclude='.git' banner-frontend/build/ ${{ secrets.USERNAME }}@${{ secrets.SERVER_IP }}:/home/vivek_project/banner-frontend/

    # Manage Backend Application with PM2
    - name: Restart Backend Application with PM2
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.USERNAME }}@${{ secrets.SERVER_IP }} "/usr/local/bin/pm2 restart banner-backend-app --update-env || /usr/local/bin/pm2 start /home/vivek_project/banner-backend/index.js --name banner-backend-app --update-env"

    # Manage Frontend Application with PM2
    - name: Serve Frontend Application with PM2
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.USERNAME }}@${{ secrets.SERVER_IP }} "/usr/local/bin/pm2 restart banner-frontend-app || /usr/local/bin/pm2 start /home/vivek_project/banner-frontend/server.js --name banner-frontend-app"

    # Ensure PM2 Startup on Reboot
    - name: Ensure PM2 Startup on Reboot
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.USERNAME }}@${{ secrets.SERVER_IP }} "/usr/local/bin/pm2 startup && /usr/local/bin/pm2 save"
